[package]
name = "deptool"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clang = "2.0.0"
clap = { version = "4.5.8", features = ["derive"] }
fnv = "1.0.7"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
